# Default values for spring-boot-admin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: azamat2115/orange
  pullPolicy: IfNotPresent
  tag: "1.0"

namespace: default
# use helmv3 install --set multi.namespaced=false for subway where all Java services are located in one namespace in EKS
# so that Role and RoleBinding will be created instead of ClusterRole and ClusterRoleBinding
#multi:
#  namespaced: true

podSecurityContext: {}

service:
  type: ClusterIP
  ports:
    port: 81
    probes: 88

#server:
#  port: 8080

app:
#  context: admin
  serviceLabelNameValue:
    type: "spring"

# use helmv3 install --set ui.title="Project Name Spring Boot Admin" if you want to customise UI brand and title
#ui:
#  title: 'Spring Boot Admin'

#serviceAccount:
#  create: true
#  annotations: {}
#  annotations:
#    eks.amazonaws.com/role-arn: arn:aws:iam::awsAccountId:role/projectName/awsEnv/eks-spring-boot-admin

# Only used with AWS and provisioning IAM: arn:aws:iam::awsAccountId:role/projectName/awsEnv/eks-spring-boot-admin , also see _helpers.tpl
#awsAccountId: setme
#awsEnv: setme

opts:
  java: -Xmx512m

resources:
  requests:
    memory: 600Mi
    cpu: 200m

livenessProbe:
  initialDelaySeconds: 120
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3
  httpGet:
    path: "/actuator/health/liveness"
    port: probes

readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 12
  httpGet:
    path: "/actuator/health/readiness"
    port: probes

nodeSelector: {}

affinity: {}

secrets: {}

tolerations: []