apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    type: {{.Values.app.serviceLabelNameValue.type}}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.ports.port }}
      targetPort: http
      protocol: TCP
    - name: probes
      port: {{ .Values.service.ports.probes }}
      targetPort: probes
      protocol: TCP